server:
  port: 8081
  connection-timeout: 6000
keycloak:
  realm: demo
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  #keycloak resource is the client ID
  resource: demo-client
  use-resource-role-mappings: true
  #The line below will prevent redirect to login page
  bearer-only: true